kafka:
  enabled: true
#  imageTag: wurstmeister/kafka:1.0.0
  replicas: 1
  zookeeper:
    enabled: true
keycloak:
  enabled: true
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
  persistence:
    # Disable deployment of the PostgreSQL chart
    deployPostgres: true

    # The database vendor. Can be either "postgres", "mysql", "mariadb", or "h2"
    dbVendor: postgres

    dbName: keycloak
    dbHost: mykeycloak
    dbPort: 5432
    dbUser: keycloak

    # Only used if no existing secret is specified. In this case a new secret is created
    dbPassword: QkQ2N05WajJZbwo=