apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hazelcast-management-center
version: '2'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast-management-center
    spec:
      containers:
      - name: hazelcast-mgnt-ctr
        image: hazelcast/management-center:3.9.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8180
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast-management-center-3.9.3
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
spec:
  ports:
  - name: http
    port: 8180
  selector:
    app: hazelcast